---
title: "BabyView Developmental Analysis"
format: html
---

```{r}
# remotes::install_github("babyview-project/babyviewr")
library(tidyverse)
library(babyviewr)
library(lubridate)
library(ggthemes)
```

```{r}
# Load the data
participants <- babyviewr::get_participant_data(include_demographics = TRUE)
recordings <- babyviewr::get_main_recording_data(include_luna = TRUE)
```

```{r}
d <- left_join(recordings, 
                      participants |>
                        filter(dataset %in% c("BV-main","Luna")) |>
                        select(-dataset), by = "subject_id") |>
  group_by(subject_id) |>
  arrange(date_time) |>
  mutate(age = date(date_time) - date_birth_rounded, 
         cumulative_hrs = cumsum(duration_hrs), 
         age_mo = floor(as.numeric(age)/30.3))


ggplot(filter(d, dataset == "BV-main"), 
       aes(x = age/30.3, y = cumulative_hrs, col = subject_id)) + 
  geom_point(alpha= .1) + 
  geom_point(data = filter(d, dataset == "Luna"), col = "black") + 
  scale_color_discrete(guide = FALSE) + 
  theme_few() + 
  xlab("Age (months)") + 
  ylab("Cumulative hours of data")
```

```{r}
age_density <- d |>
  group_by(age_mo, dataset) |>
  summarise(n = n(), 
            n_participants = n_distinct(subject_id), 
            n_hours = sum(duration_hrs))

ggplot(age_density, aes(x = age_mo, y = n_hours, fill = dataset)) + 
  geom_bar(stat = "identity") + 
  xlab("Age (months)") + 
  ylab("Total hours of data") + 
  scale_fill_solarized() +
  theme_few()
```
# Poses


```{r}
poses <- read_csv("frame_data/pose_10000.csv")

```
Looks like some of the 10k sample frames are from Bing. 

```{r}
poses$superseded_gcp_name_feb25[!(poses$superseded_gcp_name_feb25 %in% recordings$superseded_gcp_name_feb25)]

# any(recordings$superseded_gcp_name_feb25 == "01420001_2024-05-20_1_10a1a67ed7", na.rm=TRUE)

```

Merge in the data

```{r}

poses_joined <- inner_join(poses, d, by = c("superseded_gcp_name_feb25" = "superseded_gcp_name_feb25"))
```


```{r}
pose_ms <- poses_joined |>
  group_by(age_mo) |>
  summarise(n = n(), 
            body = mean(body_in_image), 
            face = mean(face_in_image), 
            hand = mean(hands_in_image)) |>
  pivot_longer(cols = c("body", "face", "hand"), 
               names_to = "part", values_to = "prop")
  

ggplot(pose_ms, aes(x = age_mo, y = prop, col = part)) + 
  geom_point(aes(size = n)) + 
  geom_smooth(method = "lm")
```

# Objects

```{r}
objects <- read_csv("frame_data/yoloe_1k_frames_fixed_ids.csv")
length(unique(objects$superseded_gcp_name_feb25))
```

```{r}
objects_joined <- inner_join(objects, d, by = c("superseded_gcp_name_feb25"))
length(unique(objects_joined$superseded_gcp_name_feb25))
```

Spot checks. Some are missing because Bing (maybe 110?)

```{r}
objects$superseded_gcp_name_feb25[!(objects$superseded_gcp_name_feb25 %in% recordings$superseded_gcp_name_feb25)]

any(objects$superseded_gcp_name_feb25 == "00510002_2024-08-12_2_dfc73374a", na.rm=TRUE)
any(recordings$superseded_gcp_name_feb25 == "00510002_2024-08-12_2_dfc73374a", na.rm=TRUE)

filter(recordings, unique_video_id == "recXBjCoaczhhbeef")$superseded_gcp_name_feb25
"00510002_2024-08-12_2_dfc73374ae"

unique(objects$superseded_gcp_name_feb25[!(objects$superseded_gcp_name_feb25 %in% recordings$superseded_gcp_name_feb25)])
```


```{r}
object_ms <- objects_joined |>
  group_by(age_mo, superseded_gcp_name_feb25) |>
  summarise(n = n(), 
            pixels = mean(masked_pixel_count)) |>
  group_by(age_mo) |>
  summarise(n_objs = mean(n), 
            n= n(), 
            pixels = mean(pixels))
  
ggplot(object_ms, aes(x = age_mo, y = n_objs)) + 
  geom_point(aes(size = n)) + 
  geom_smooth(method = "lm") + 
  ylab("Number of objects in frame (average)") +
  xlab("Age (months)")

ggplot(object_ms, aes(x = age_mo, y = pixels)) + 
  geom_point(aes(size = n)) + 
  geom_smooth(method = "lm") + 
  ylab("Size of objects in frame (px)") +
  xlab("Age (months)")
```
```{r}
object_freq <- objects_joined %>%
  group_by(class_name) %>%
  summarize(count = n())  %>%
  arrange(count) %>%
  slice_max(n=50, order_by=count)
```

```{r}

ggplot(data=object_freq, aes(x=fct_reorder(class_name, count, .desc=FALSE), y=count)) +
  theme_few(base_size=6) +
  geom_point(alpha=.8) +
  coord_flip() +
  xlab('Top 50 objects detected') +
  ylab('# of detections in 1000 frames')
```


```{r}
aoa = read_csv(here::here('cdi_data_march_2025/MCDI_items_with_AoA.csv'))
```
