---
title: "BabyView Developmental Analysis"
format: html
---

```{r}
# remotes::install_github("babyview-project/babyviewr")
library(tidyverse)
library(babyviewr)
library(lubridate)
library(ggthemes)
library(kableExtra)
library(here)

DATA_LOC = here("data")
```

```{r}
# Load the data
participants <- babyviewr::get_participant_data(include_demographics = TRUE)
recordings <- babyviewr::get_main_recording_data(include_luna = TRUE)
```

```{r}
d <- left_join(recordings, 
                      participants |>
                        filter(dataset %in% c("BV-main","Luna")) |>
                        select(-dataset), by = "subject_id") |>
  group_by(subject_id) |>
  arrange(date_time) |>
  mutate(age = date(date_time) - date_birth_rounded, 
         cumulative_hrs = cumsum(duration_hrs), 
         age_mo = floor(as.numeric(age)/30.3))


ggplot(filter(d, dataset == "BV-main"), 
       aes(x = age/30.3, y = cumulative_hrs, col = subject_id)) + 
  geom_point(alpha= .1) + 
  geom_point(data = filter(d, dataset == "Luna"), col = "black") + 
  scale_color_discrete(guide = FALSE) + 
  theme_few() + 
  xlab("Age (months)") + 
  ylab("Cumulative hours of data")
```

```{r}
age_density <- d |>
  group_by(age_mo, dataset) |>
  summarise(n = n(), 
            n_participants = n_distinct(subject_id), 
            n_hours = sum(duration_hrs))

ggplot(age_density, aes(x = age_mo, y = n_hours, fill = dataset)) + 
  geom_bar(stat = "identity") + 
  xlab("Age (months)") + 
  ylab("Total hours of data") + 
  scale_fill_solarized() +
  theme_few()
```
# Poses


```{r}
poses <- read_csv(here(DATA_LOC, "frame_data", "pose_10000.csv"))

```
Looks like some of the 10k sample frames are from Bing. 
Looks to be about ~1000 frames, not included in this analysis
```{r}
length(poses$superseded_gcp_name_feb25[!(poses$superseded_gcp_name_feb25 %in% recordings$superseded_gcp_name_feb25)])

# any(recordings$superseded_gcp_name_feb25 == "01420001_2024-05-20_1_10a1a67ed7", na.rm=TRUE)

```

Merge in the data
```{r}
poses_joined <- inner_join(poses, d, by = c("superseded_gcp_name_feb25" = "superseded_gcp_name_feb25"))
```


```{r}
pose_ms <- poses_joined |>
  group_by(age_mo) |>
  summarise(n = n(), 
            body = mean(body_in_image), 
            face = mean(face_in_image), 
            hand = mean(hands_in_image)) |>
  pivot_longer(cols = c("body", "face", "hand"), 
               names_to = "part", values_to = "prop")
  

ggplot(pose_ms, aes(x = age_mo, y = prop, col = part)) + 
  geom_point(aes(size = n)) + 
  geom_smooth(method = "lm")
```

# Objects
```{r}
objects <- read_csv(here(DATA_LOC, "frame_data", "yoloe_10k_frames.csv"))
objects_joined <- inner_join(objects, d, by = c("superseded_gcp_name_feb25"))

# any(recordings$superseded_gcp_name_feb25 == "00510002_2024-08-12_2_dfc73374a", na.rm=TRUE)

# objects$superseded_gcp_name_feb25[!(objects$superseded_gcp_name_feb25 %in% recordings$superseded_gcp_name_feb25)]
```


```{r}
object_ms <- objects_joined |>
  group_by(age_mo, subject_id, superseded_gcp_name_feb25) |>
  summarise(n = n(), 
            pixels = mean(masked_pixel_count, na.rm=TRUE)) |>
  group_by(age_mo, subject_id) |>
  summarise(n_objs = mean(n), 
            n= n(), 
            pixels = mean(pixels, na.rm=TRUE))
  
```

```{r}
ggplot(object_ms, aes(x = age_mo, y = n_objs, col=subject_id)) + 
  geom_point(aes(size = n), alpha=.2) + 
  geom_smooth(method = "lm", alpha=.1) +
  ggtitle('Number of objects by age') +
  xlab('Age in months') +
  ylab('Count objects detected') +
  theme(legend.position = 'none')
```

```{r}
ggplot(object_ms, aes(x = age_mo, y = pixels, col=subject_id)) + 
  geom_point(aes(size = n), alpha=.2) + 
  geom_smooth(method = "lm", alpha=.1) +
  xlab('Age in months') +
  theme(legend.position = 'none') +
  ggtitle('Size of objects by age') +
  xlab('Age in months') +
  ylab('Average pixel count of detected objs') 
```

Calculate raw counts (not normalizing here)
```{r}
object_count <- objects_joined %>%
  group_by(class_name) %>%
  summarize(count = n())  %>%
  arrange(count)  

kable(object_count %>% arrange(-count))
```

```{R}
object_counts_expanded_dataframe <- objects_joined %>%
  group_by(superseded_gcp_name_feb25, class_name) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  complete(superseded_gcp_name_feb25, class_name, fill = list(count = 0)) %>%
  mutate(class_present = count>0)   %>%
  filter(!is.na(class_name)) # this comes from frames that had nothing, but doesn't need to be in list of objects
```

```{R}
object_freq <- object_counts_expanded_dataframe %>%
  group_by(class_name) %>%
  summarize(freq = mean(class_present)) %>%
  arrange(freq)
```

Plot top 50 objects in the 10k frame detections
```{r}
ggplot(data=object_count %>% slice_max(n=50, order_by=count), aes(x=fct_reorder(class_name, count, .desc=FALSE), y=count)) +
  theme_few(base_size=6) +
  geom_point(alpha=.8) +
  coord_flip() +
  xlab('Top 50 objects detected') +
  ylab('# of detections in 10000 frames')
```

```{r}
ggplot(data=object_freq %>% slice_max(n=50, order_by=freq), aes(x=fct_reorder(class_name, freq, .desc=FALSE), y=freq)) +
  theme_few(base_size=6) +
  geom_point(alpha=.8) +
  coord_flip() +
  xlab('Top 50 objects detected') +
  ylab('Freq of detections in 1000 frames')
```

Load aoa data for specific items
```{r}
aoa = read_csv(here(DATA_LOC, "cdi_data_march_2025", "MCDI_items_with_AoA.csv")) %>%
  select(english_gloss, AoA) %>%
  rename(class_name = english_gloss)
```

Join with aoa data
```{r}
object_freq_with_aoa <- object_freq %>%
  left_join(aoa) 
```
```{r}
object_freq_with_aoa <- object_freq %>%
  left_join(aoa) %>%
  # filter(!class_name %in% c('tv','book','person','toy','chair')) %>% # these seem like objects that contain multiple objects/content...
  filter(!is.na(AoA)) # don't have some aoas
```

```{r}
ggplot(data=object_freq_with_aoa, aes(x=freq, y=AoA, label=class_name)) +
  geom_point(alpha=.4) +
  xlab('Frequency of objects') +
  ylab('AoA') +
  ggrepel::geom_label_repel() +
  geom_smooth(method='lm')  +
  theme_few(base_size=10)  

```
